/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.parser;

import minijava.lexer.*;
import minijava.node.*;
import minijava.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AProgram */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AMainClass */
		    {
			ArrayList list = new1();
			push(goTo(1), list);
		    }
		    break;
                    case 2: /* reduce AExtClassDecl */
		    {
			ArrayList list = new2();
			push(goTo(2), list);
		    }
		    break;
                    case 3: /* reduce ANonextClassDecl */
		    {
			ArrayList list = new3();
			push(goTo(2), list);
		    }
		    break;
                    case 4: /* reduce AEmptyClassDecl */
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;
                    case 5: /* reduce ANonemptyVarDecl */
		    {
			ArrayList list = new5();
			push(goTo(3), list);
		    }
		    break;
                    case 6: /* reduce AEmptyVarDecl */
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;
                    case 7: /* reduce ANonemptyMethodDecl */
		    {
			ArrayList list = new7();
			push(goTo(4), list);
		    }
		    break;
                    case 8: /* reduce AEmptyMethodDecl */
		    {
			ArrayList list = new8();
			push(goTo(4), list);
		    }
		    break;
                    case 9: /* reduce ANonemptyFormallist */
		    {
			ArrayList list = new9();
			push(goTo(5), list);
		    }
		    break;
                    case 10: /* reduce AEmptyFormallist */
		    {
			ArrayList list = new10();
			push(goTo(5), list);
		    }
		    break;
                    case 11: /* reduce ARemainderFormalrest */
		    {
			ArrayList list = new11();
			push(goTo(6), list);
		    }
		    break;
                    case 12: /* reduce AEmptyFormalrest */
		    {
			ArrayList list = new12();
			push(goTo(6), list);
		    }
		    break;
                    case 13: /* reduce ANonemptyStatementlist */
		    {
			ArrayList list = new13();
			push(goTo(7), list);
		    }
		    break;
                    case 14: /* reduce AEmptyStatementlist */
		    {
			ArrayList list = new14();
			push(goTo(7), list);
		    }
		    break;
                    case 15: /* reduce AOpenStatement */
		    {
			ArrayList list = new15();
			push(goTo(8), list);
		    }
		    break;
                    case 16: /* reduce AClosedStatement */
		    {
			ArrayList list = new16();
			push(goTo(8), list);
		    }
		    break;
                    case 17: /* reduce AIfStatement1 */
		    {
			ArrayList list = new17();
			push(goTo(9), list);
		    }
		    break;
                    case 18: /* reduce AIfelseStatement1 */
		    {
			ArrayList list = new18();
			push(goTo(9), list);
		    }
		    break;
                    case 19: /* reduce AWhileStatement1 */
		    {
			ArrayList list = new19();
			push(goTo(9), list);
		    }
		    break;
                    case 20: /* reduce ANestedStatement2 */
		    {
			ArrayList list = new20();
			push(goTo(10), list);
		    }
		    break;
                    case 21: /* reduce AIfelseStatement2 */
		    {
			ArrayList list = new21();
			push(goTo(10), list);
		    }
		    break;
                    case 22: /* reduce AWhileStatement2 */
		    {
			ArrayList list = new22();
			push(goTo(10), list);
		    }
		    break;
                    case 23: /* reduce APrintStatement2 */
		    {
			ArrayList list = new23();
			push(goTo(10), list);
		    }
		    break;
                    case 24: /* reduce AAssignStatement2 */
		    {
			ArrayList list = new24();
			push(goTo(10), list);
		    }
		    break;
                    case 25: /* reduce AVassignStatement2 */
		    {
			ArrayList list = new25();
			push(goTo(10), list);
		    }
		    break;
                    case 26: /* reduce AInttType */
		    {
			ArrayList list = new26();
			push(goTo(11), list);
		    }
		    break;
                    case 27: /* reduce AIntvType */
		    {
			ArrayList list = new27();
			push(goTo(11), list);
		    }
		    break;
                    case 28: /* reduce ABoolType */
		    {
			ArrayList list = new28();
			push(goTo(11), list);
		    }
		    break;
                    case 29: /* reduce AObjectType */
		    {
			ArrayList list = new29();
			push(goTo(11), list);
		    }
		    break;
                    case 30: /* reduce ANameNoarrayexpr */
		    {
			ArrayList list = new30();
			push(goTo(12), list);
		    }
		    break;
                    case 31: /* reduce ALiteralNoarrayexpr */
		    {
			ArrayList list = new31();
			push(goTo(12), list);
		    }
		    break;
                    case 32: /* reduce ATrueNoarrayexpr */
		    {
			ArrayList list = new32();
			push(goTo(12), list);
		    }
		    break;
                    case 33: /* reduce AFalseNoarrayexpr */
		    {
			ArrayList list = new33();
			push(goTo(12), list);
		    }
		    break;
                    case 34: /* reduce AThisNoarrayexpr */
		    {
			ArrayList list = new34();
			push(goTo(12), list);
		    }
		    break;
                    case 35: /* reduce AParexpNoarrayexpr */
		    {
			ArrayList list = new35();
			push(goTo(12), list);
		    }
		    break;
                    case 36: /* reduce AVaccessNoarrayexpr */
		    {
			ArrayList list = new36();
			push(goTo(12), list);
		    }
		    break;
                    case 37: /* reduce ALengthNoarrayexpr */
		    {
			ArrayList list = new37();
			push(goTo(12), list);
		    }
		    break;
                    case 38: /* reduce AMaccessNoarrayexpr */
		    {
			ArrayList list = new38();
			push(goTo(12), list);
		    }
		    break;
                    case 39: /* reduce ANewcNoarrayexpr */
		    {
			ArrayList list = new39();
			push(goTo(12), list);
		    }
		    break;
                    case 40: /* reduce ANewarrPrimaryexpr */
		    {
			ArrayList list = new40();
			push(goTo(13), list);
		    }
		    break;
                    case 41: /* reduce ANextPrimaryexpr */
		    {
			ArrayList list = new41();
			push(goTo(13), list);
		    }
		    break;
                    case 42: /* reduce ANonemptyMatrixaccess */
		    {
			ArrayList list = new42();
			push(goTo(14), list);
		    }
		    break;
                    case 43: /* reduce AEmptyMatrixaccess */
		    {
			ArrayList list = new43();
			push(goTo(14), list);
		    }
		    break;
                    case 44: /* reduce ANotUnaryexpr */
		    {
			ArrayList list = new44();
			push(goTo(15), list);
		    }
		    break;
                    case 45: /* reduce ANextUnaryexpr */
		    {
			ArrayList list = new45();
			push(goTo(15), list);
		    }
		    break;
                    case 46: /* reduce ATimesIpexpr */
		    {
			ArrayList list = new46();
			push(goTo(16), list);
		    }
		    break;
                    case 47: /* reduce ANextIpexpr */
		    {
			ArrayList list = new47();
			push(goTo(16), list);
		    }
		    break;
                    case 48: /* reduce APlusIaexpr */
		    {
			ArrayList list = new48();
			push(goTo(17), list);
		    }
		    break;
                    case 49: /* reduce AMinusIaexpr */
		    {
			ArrayList list = new49();
			push(goTo(17), list);
		    }
		    break;
                    case 50: /* reduce ANextIaexpr */
		    {
			ArrayList list = new50();
			push(goTo(17), list);
		    }
		    break;
                    case 51: /* reduce AGreaterBexpr */
		    {
			ArrayList list = new51();
			push(goTo(18), list);
		    }
		    break;
                    case 52: /* reduce AGeBexpr */
		    {
			ArrayList list = new52();
			push(goTo(18), list);
		    }
		    break;
                    case 53: /* reduce ALessBexpr */
		    {
			ArrayList list = new53();
			push(goTo(18), list);
		    }
		    break;
                    case 54: /* reduce ALeBexpr */
		    {
			ArrayList list = new54();
			push(goTo(18), list);
		    }
		    break;
                    case 55: /* reduce ANextBexpr */
		    {
			ArrayList list = new55();
			push(goTo(18), list);
		    }
		    break;
                    case 56: /* reduce AAndExpr */
		    {
			ArrayList list = new56();
			push(goTo(19), list);
		    }
		    break;
                    case 57: /* reduce AOrExpr */
		    {
			ArrayList list = new57();
			push(goTo(19), list);
		    }
		    break;
                    case 58: /* reduce ALogicalequalExpr */
		    {
			ArrayList list = new58();
			push(goTo(19), list);
		    }
		    break;
                    case 59: /* reduce ANoteqExpr */
		    {
			ArrayList list = new59();
			push(goTo(19), list);
		    }
		    break;
                    case 60: /* reduce ANextExpr */
		    {
			ArrayList list = new60();
			push(goTo(19), list);
		    }
		    break;
                    case 61: /* reduce ANonemptyExprlist */
		    {
			ArrayList list = new61();
			push(goTo(20), list);
		    }
		    break;
                    case 62: /* reduce AEmptyExprlist */
		    {
			ArrayList list = new62();
			push(goTo(20), list);
		    }
		    break;
                    case 63: /* reduce ARemainderExprrest */
		    {
			ArrayList list = new63();
			push(goTo(21), list);
		    }
		    break;
                    case 64: /* reduce AEmptyExprrest */
		    {
			ArrayList list = new64();
			push(goTo(21), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainClass pmainclassNode2;
        LinkedList listNode4 = new LinkedList();
        pmainclassNode2 = (PMainClass)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AProgram(pmainclassNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AMainClass */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList17 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList16 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList15 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMainClass pmainclassNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        PStatement pstatementNode4;
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList12.get(0);
        pstatementNode4 = (PStatement)nodeArrayList15.get(0);

        pmainclassNode1 = new AMainClass(tidNode2, tidNode3, pstatementNode4);
        }
	nodeList.add(pmainclassNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AExtClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode9 = new LinkedList();
        {
            // Block
        PClassDecl pclassdeclNode1;
        LinkedList listNode8 = new LinkedList();
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList6.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList7.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, tidNode3, listNode5, listNode7);
        }
        listNode8 = (LinkedList)nodeArrayList9.get(0);
	if(pclassdeclNode1 != null)
	{
	  listNode9.add(pclassdeclNode1);
	}
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
	nodeList.add(listNode9);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce ANonextClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode9 = new LinkedList();
        {
            // Block
        PClassDecl pclassdeclNode1;
        LinkedList listNode8 = new LinkedList();
        {
            // Block
        TId tidNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList5.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pclassdeclNode1 = new AClassDecl(tidNode2, null, listNode5, listNode7);
        }
        listNode8 = (LinkedList)nodeArrayList7.get(0);
	if(pclassdeclNode1 != null)
	{
	  listNode9.add(pclassdeclNode1);
	}
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
	nodeList.add(listNode9);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AEmptyClassDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ANonemptyVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PVarDecl pvardeclNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        {
            // Block
        PType ptypeNode3;
        TId tidNode4;
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);

        pvardeclNode2 = new AVarDecl(ptypeNode3, tidNode4);
        }
	if(listNode1 != null)
	{
	  listNode5.addAll(listNode1);
	}
	if(pvardeclNode2 != null)
	{
	  listNode5.add(pvardeclNode2);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AEmptyVarDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce ANonemptyMethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode12 = new LinkedList();
        {
            // Block
        PMethodDecl pmethoddeclNode1;
        LinkedList listNode11 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode9 = new LinkedList();
        PExp pexpNode10;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList8.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        {
            // Block
        LinkedList listNode8 = new LinkedList();
        listNode8 = (LinkedList)nodeArrayList9.get(0);
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
        pexpNode10 = (PExp)nodeArrayList11.get(0);

        pmethoddeclNode1 = new AMethodDecl(ptypeNode2, tidNode3, listNode5, listNode7, listNode9, pexpNode10);
        }
        listNode11 = (LinkedList)nodeArrayList14.get(0);
	if(pmethoddeclNode1 != null)
	{
	  listNode12.add(pmethoddeclNode1);
	}
	if(listNode11 != null)
	{
	  listNode12.addAll(listNode11);
	}
        }
	nodeList.add(listNode12);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AEmptyMethodDecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce ANonemptyFormallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        PFormal pformalNode1;
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pformalNode1 = new AFormal(ptypeNode2, tidNode3);
        }
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(pformalNode1 != null)
	{
	  listNode5.add(pformalNode1);
	}
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AEmptyFormallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce ARemainderFormalrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        PFormal pformalNode1;
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);

        pformalNode1 = new AFormal(ptypeNode2, tidNode3);
        }
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(pformalNode1 != null)
	{
	  listNode5.add(pformalNode1);
	}
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AEmptyFormalrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce ANonemptyStatementlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PStatement pstatementNode1;
        LinkedList listNode2 = new LinkedList();
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pstatementNode1 != null)
	{
	  listNode3.add(pstatementNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AEmptyStatementlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AOpenStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AClosedStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AIfStatement1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokIf ttokifNode2;
        PExp pexpNode3;
        PStatement pstatementNode4;
        @SuppressWarnings("unused") Object nullNode5 = null;
        ttokifNode2 = (TTokIf)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pstatementNode4 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AIfStatement(ttokifNode2, pexpNode3, pstatementNode4, null);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce AIfelseStatement1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokIf ttokifNode2;
        PExp pexpNode3;
        PStatement pstatementNode4;
        PStatement pstatementNode5;
        ttokifNode2 = (TTokIf)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pstatementNode4 = (PStatement)nodeArrayList5.get(0);
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AIfStatement(ttokifNode2, pexpNode3, pstatementNode4, pstatementNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AWhileStatement1 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokWhile ttokwhileNode2;
        PExp pexpNode3;
        PStatement pstatementNode4;
        ttokwhileNode2 = (TTokWhile)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pstatementNode4 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(ttokwhileNode2, pexpNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce ANestedStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TLBrace tlbraceNode2;
        LinkedList listNode4 = new LinkedList();
        tlbraceNode2 = (TLBrace)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pstatementNode1 = new ABlockStatement(tlbraceNode2, listNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AIfelseStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokIf ttokifNode2;
        PExp pexpNode3;
        PStatement pstatementNode4;
        PStatement pstatementNode5;
        ttokifNode2 = (TTokIf)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pstatementNode4 = (PStatement)nodeArrayList5.get(0);
        pstatementNode5 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AIfStatement(ttokifNode2, pexpNode3, pstatementNode4, pstatementNode5);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AWhileStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokWhile ttokwhileNode2;
        PExp pexpNode3;
        PStatement pstatementNode4;
        ttokwhileNode2 = (TTokWhile)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pstatementNode4 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(ttokwhileNode2, pexpNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce APrintStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TTokPrint ttokprintNode2;
        PExp pexpNode3;
        ttokprintNode2 = (TTokPrint)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pstatementNode1 = new APrintStatement(ttokprintNode2, pexpNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AAssignStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExp pexpNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pstatementNode1 = new AAssignStatement(tidNode2, pexpNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AVassignStatement2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExp pexpNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);
        pexpNode4 = (PExp)nodeArrayList6.get(0);

        pstatementNode1 = new AArrayAssignStatement(tidNode2, pexpNode3, pexpNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AInttType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TTokInt ttokintNode2;
        ttokintNode2 = (TTokInt)nodeArrayList1.get(0);

        ptypeNode1 = new AIntType(ttokintNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AIntvType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TTokInt ttokintNode2;
        ttokintNode2 = (TTokInt)nodeArrayList1.get(0);

        ptypeNode1 = new AArrayType(ttokintNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce ABoolType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TTokBoolean ttokbooleanNode2;
        ttokbooleanNode2 = (TTokBoolean)nodeArrayList1.get(0);

        ptypeNode1 = new ABooleanType(ttokbooleanNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce AObjectType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        ptypeNode1 = new AObjectType(tidNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce ANameNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpNode1 = new AIdentifierExp(tidNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce ALiteralNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexpNode1 = new AIntegerLiteralExp(tnumberNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce ATrueNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TTokTrue ttoktrueNode2;
        ttoktrueNode2 = (TTokTrue)nodeArrayList1.get(0);

        pexpNode1 = new ATrueExp(ttoktrueNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AFalseNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TTokFalse ttokfalseNode2;
        ttokfalseNode2 = (TTokFalse)nodeArrayList1.get(0);

        pexpNode1 = new AFalseExp(ttokfalseNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AThisNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TTokThis ttokthisNode2;
        ttokthisNode2 = (TTokThis)nodeArrayList1.get(0);

        pexpNode1 = new AThisExp(ttokthisNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce AParexpNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList2.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce AVaccessNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TLBrack tlbrackNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tlbrackNode3 = (TLBrack)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AArrayLookupExp(pexpNode2, tlbrackNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce ALengthNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TTokLength ttoklengthNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        ttoklengthNode3 = (TTokLength)nodeArrayList3.get(0);

        pexpNode1 = new AArrayLengthExp(pexpNode2, ttoklengthNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce AMaccessNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pexpNode1 = new ACallExp(pexpNode2, tidNode3, listNode5);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce ANewcNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pexpNode1 = new ANewObjectExp(tidNode2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce ANewarrPrimaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TTokNew ttoknewNode2;
        PExp pexpNode3;
        LinkedList listNode5 = new LinkedList();
        ttoknewNode2 = (TTokNew)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList6.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pexpNode1 = new ANewArrayExp(ttoknewNode2, pexpNode3, listNode5);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce ANextPrimaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce ANonemptyMatrixaccess */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        LinkedList listNode2 = new LinkedList();
        pexpNode1 = (PExp)nodeArrayList2.get(0);
        listNode2 = (LinkedList)nodeArrayList4.get(0);
	if(pexpNode1 != null)
	{
	  listNode3.add(pexpNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce AEmptyMatrixaccess */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce ANotUnaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        TNot tnotNode2;
        PExp pexpNode3;
        tnotNode2 = (TNot)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);

        pexpNode1 = new ANotExp(tnotNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce ANextUnaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ATimesIpexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TTimes ttimesNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        ttimesNode3 = (TTimes)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ATimesExp(pexpNode2, ttimesNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce ANextIpexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce APlusIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TPlus tplusNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new APlusExp(pexpNode2, tplusNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new49() /* reduce AMinusIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TMinus tminusNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AMinusExp(pexpNode2, tminusNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new50() /* reduce ANextIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new51() /* reduce AGreaterBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AGthanExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new52() /* reduce AGeBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AGeExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new53() /* reduce ALessBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TLt tltNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tltNode3 = (TLt)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ALessThanExp(pexpNode2, tltNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new54() /* reduce ALeBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ALthanExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new55() /* reduce ANextBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new56() /* reduce AAndExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TAnd tandNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        tandNode3 = (TAnd)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AAndExp(pexpNode2, tandNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new57() /* reduce AOrExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AOrExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new58() /* reduce ALogicalequalExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TEq teqNode3;
        PExp pexpNode4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        teqNode3 = (TEq)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new AEqualExp(pexpNode2, teqNode3, pexpNode4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new59() /* reduce ANoteqExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        PExp pexpNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList3.get(0);

        pexpNode1 = new ANoteqExp(pexpNode2, pexpNode3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new60() /* reduce ANextExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        pexpNode1 = (PExp)nodeArrayList1.get(0);
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new61() /* reduce ANonemptyExprlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        LinkedList listNode2 = new LinkedList();
        pexpNode1 = (PExp)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pexpNode1 != null)
	{
	  listNode3.add(pexpNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new62() /* reduce AEmptyExprlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new63() /* reduce ARemainderExprrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExp pexpNode1;
        LinkedList listNode2 = new LinkedList();
        pexpNode1 = (PExp)nodeArrayList2.get(0);
        listNode2 = (LinkedList)nodeArrayList3.get(0);
	if(pexpNode1 != null)
	{
	  listNode3.add(pexpNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new64() /* reduce AEmptyExprrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {2, SHIFT, 1}, },
			{{-1, ERROR, 1}, {42, SHIFT, 4}, },
			{{-1, ERROR, 2}, {44, ACCEPT, -1}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 5}, },
			{{-1, ERROR, 4}, {24, SHIFT, 7}, },
			{{-1, ERROR, 5}, {42, SHIFT, 8}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 7}, {3, SHIFT, 9}, },
			{{-1, ERROR, 8}, {4, SHIFT, 10}, {24, SHIFT, 11}, },
			{{-1, ERROR, 9}, {16, SHIFT, 12}, },
			{{-1, ERROR, 10}, {42, SHIFT, 13}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 12}, {17, SHIFT, 15}, },
			{{-1, ERROR, 13}, {24, SHIFT, 16}, },
			{{-1, REDUCE, 8}, {0, SHIFT, 17}, {1, SHIFT, 18}, {3, SHIFT, 19}, {42, SHIFT, 20}, },
			{{-1, ERROR, 15}, {18, SHIFT, 23}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 26}, {20, SHIFT, 25}, },
			{{-1, REDUCE, 28}, },
			{{-1, ERROR, 19}, {0, SHIFT, 17}, {1, SHIFT, 18}, {42, SHIFT, 20}, },
			{{-1, REDUCE, 29}, },
			{{-1, ERROR, 21}, {25, SHIFT, 27}, },
			{{-1, ERROR, 22}, {42, SHIFT, 28}, },
			{{-1, ERROR, 23}, {22, SHIFT, 29}, },
			{{-1, REDUCE, 8}, {0, SHIFT, 17}, {1, SHIFT, 18}, {3, SHIFT, 19}, {42, SHIFT, 20}, },
			{{-1, ERROR, 25}, {21, SHIFT, 31}, },
			{{-1, ERROR, 26}, {42, SHIFT, 32}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 5}, },
			{{-1, ERROR, 28}, {28, SHIFT, 34}, },
			{{-1, ERROR, 29}, {14, SHIFT, 35}, },
			{{-1, ERROR, 30}, {25, SHIFT, 36}, },
			{{-1, REDUCE, 27}, },
			{{-1, ERROR, 32}, {22, SHIFT, 37}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 35}, {20, SHIFT, 38}, },
			{{-1, REDUCE, 4}, {2, SHIFT, 5}, },
			{{-1, REDUCE, 10}, {0, SHIFT, 17}, {1, SHIFT, 18}, {42, SHIFT, 20}, },
			{{-1, ERROR, 38}, {21, SHIFT, 42}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 40}, {23, SHIFT, 43}, },
			{{-1, ERROR, 41}, {42, SHIFT, 44}, },
			{{-1, ERROR, 42}, {42, SHIFT, 45}, },
			{{-1, ERROR, 43}, {24, SHIFT, 46}, },
			{{-1, REDUCE, 12}, {27, SHIFT, 47}, },
			{{-1, ERROR, 45}, {23, SHIFT, 49}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 47}, {0, SHIFT, 17}, {1, SHIFT, 18}, {42, SHIFT, 20}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 49}, {24, SHIFT, 52}, },
			{{-1, REDUCE, 14}, {0, SHIFT, 17}, {1, SHIFT, 18}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 57}, },
			{{-1, ERROR, 51}, {42, SHIFT, 62}, },
			{{-1, ERROR, 52}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, ERROR, 53}, {22, SHIFT, 65}, },
			{{-1, ERROR, 54}, {22, SHIFT, 66}, },
			{{-1, ERROR, 55}, {22, SHIFT, 67}, },
			{{-1, REDUCE, 14}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, REDUCE, 29}, {20, SHIFT, 69}, {41, SHIFT, 70}, },
			{{-1, ERROR, 58}, {8, SHIFT, 71}, },
			{{-1, REDUCE, 14}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 12}, {27, SHIFT, 47}, },
			{{-1, ERROR, 63}, {20, SHIFT, 69}, {41, SHIFT, 70}, },
			{{-1, ERROR, 64}, {25, SHIFT, 74}, },
			{{-1, ERROR, 65}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 66}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 67}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 68}, {25, SHIFT, 92}, },
			{{-1, ERROR, 69}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 70}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 71}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 74}, {25, SHIFT, 96}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 78}, {0, SHIFT, 97}, {42, SHIFT, 98}, },
			{{-1, ERROR, 79}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 80}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 41}, {20, SHIFT, 101}, },
			{{-1, REDUCE, 45}, {26, SHIFT, 102}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 50}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 55}, {29, SHIFT, 104}, {30, SHIFT, 105}, },
			{{-1, REDUCE, 60}, {32, SHIFT, 106}, {33, SHIFT, 107}, {34, SHIFT, 108}, {35, SHIFT, 109}, },
			{{-1, ERROR, 89}, {23, SHIFT, 110}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, ERROR, 90}, {23, SHIFT, 115}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, ERROR, 91}, {23, SHIFT, 116}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 93}, {21, SHIFT, 117}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, ERROR, 94}, {28, SHIFT, 118}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, ERROR, 95}, {28, SHIFT, 119}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 97}, {20, SHIFT, 120}, },
			{{-1, ERROR, 98}, {22, SHIFT, 121}, },
			{{-1, ERROR, 99}, {23, SHIFT, 122}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 101}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 102}, {13, SHIFT, 124}, {42, SHIFT, 125}, },
			{{-1, ERROR, 103}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 104}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 105}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 106}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 107}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 108}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 109}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 110}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, ERROR, 111}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 112}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 113}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 114}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 115}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, ERROR, 116}, {28, SHIFT, 141}, },
			{{-1, ERROR, 117}, {41, SHIFT, 142}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 119}, {25, SHIFT, 143}, },
			{{-1, ERROR, 120}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 121}, {23, SHIFT, 145}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 123}, {21, SHIFT, 146}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 125}, {22, SHIFT, 147}, },
			{{-1, REDUCE, 46}, },
			{{-1, REDUCE, 48}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 49}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 51}, {29, SHIFT, 104}, {30, SHIFT, 105}, },
			{{-1, REDUCE, 53}, {29, SHIFT, 104}, {30, SHIFT, 105}, },
			{{-1, REDUCE, 52}, {29, SHIFT, 104}, {30, SHIFT, 105}, },
			{{-1, REDUCE, 54}, {29, SHIFT, 104}, {30, SHIFT, 105}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 16}, {7, SHIFT, 148}, },
			{{-1, REDUCE, 56}, {32, SHIFT, 106}, {33, SHIFT, 107}, {34, SHIFT, 108}, {35, SHIFT, 109}, },
			{{-1, REDUCE, 57}, {32, SHIFT, 106}, {33, SHIFT, 107}, {34, SHIFT, 108}, {35, SHIFT, 109}, },
			{{-1, REDUCE, 58}, {32, SHIFT, 106}, {33, SHIFT, 107}, {34, SHIFT, 108}, {35, SHIFT, 109}, },
			{{-1, REDUCE, 59}, {32, SHIFT, 106}, {33, SHIFT, 107}, {34, SHIFT, 108}, {35, SHIFT, 109}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 142}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, REDUCE, 8}, {3, SHIFT, 19}, },
			{{-1, ERROR, 144}, {21, SHIFT, 151}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 36}, },
			{{-1, REDUCE, 62}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, ERROR, 148}, {5, SHIFT, 53}, {6, SHIFT, 54}, {15, SHIFT, 55}, {24, SHIFT, 56}, {42, SHIFT, 63}, },
			{{-1, ERROR, 149}, {28, SHIFT, 156}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 43}, {20, SHIFT, 157}, },
			{{-1, REDUCE, 64}, {27, SHIFT, 159}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, ERROR, 153}, {23, SHIFT, 161}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 157}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 159}, {9, SHIFT, 75}, {10, SHIFT, 76}, {11, SHIFT, 77}, {12, SHIFT, 78}, {22, SHIFT, 79}, {40, SHIFT, 80}, {42, SHIFT, 81}, {43, SHIFT, 82}, },
			{{-1, REDUCE, 61}, },
			{{-1, REDUCE, 38}, },
			{{-1, ERROR, 162}, {21, SHIFT, 164}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 64}, {27, SHIFT, 159}, {36, SHIFT, 111}, {37, SHIFT, 112}, {38, SHIFT, 113}, {39, SHIFT, 114}, },
			{{-1, REDUCE, 43}, {20, SHIFT, 157}, },
			{{-1, REDUCE, 63}, },
			{{-1, REDUCE, 42}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 6}, {27, 33}, {36, 39}, },
			{{-1, 14}, {16, 24}, {46, 50}, },
			{{-1, 21}, {24, 30}, {143, 150}, },
			{{-1, 40}, },
			{{-1, 48}, {62, 73}, },
			{{-1, 58}, {56, 68}, {59, 72}, },
			{{-1, 59}, {52, 64}, {110, 133}, },
			{{-1, 60}, {115, 139}, {148, 154}, },
			{{-1, 61}, {110, 134}, {115, 140}, {148, 155}, },
			{{-1, 22}, {19, 26}, {37, 41}, {47, 51}, },
			{{-1, 83}, },
			{{-1, 84}, },
			{{-1, 158}, {164, 166}, },
			{{-1, 85}, {80, 100}, {103, 126}, },
			{{-1, 86}, {104, 127}, {105, 128}, },
			{{-1, 87}, {106, 129}, {107, 130}, {108, 131}, {109, 132}, },
			{{-1, 88}, {111, 135}, {112, 136}, {113, 137}, {114, 138}, },
			{{-1, 89}, {66, 90}, {67, 91}, {69, 93}, {70, 94}, {71, 95}, {79, 99}, {101, 123}, {120, 144}, {142, 149}, {147, 152}, {157, 162}, {159, 163}, },
			{{-1, 153}, },
			{{-1, 160}, {163, 165}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'class'",
			"expecting: id",
			"expecting: EOF",
			"expecting: 'class', EOF",
			"expecting: '{'",
			"expecting: 'public'",
			"expecting: 'extends', '{'",
			"expecting: 'static'",
			"expecting: 'int', 'boolean', 'public', '}', id",
			"expecting: 'void'",
			"expecting: 'main'",
			"expecting: '[', id",
			"expecting: 'int', 'boolean', id",
			"expecting: '}'",
			"expecting: '('",
			"expecting: ']'",
			"expecting: ';'",
			"expecting: 'String'",
			"expecting: 'int', 'boolean', 'public', 'if', 'while', 'return', 'System.out.println', '{', '}', id",
			"expecting: '['",
			"expecting: 'int', 'boolean', ')', id",
			"expecting: ')'",
			"expecting: ')', ','",
			"expecting: 'int', 'boolean', 'if', 'while', 'return', 'System.out.println', '{', id",
			"expecting: 'if', 'while', 'System.out.println', '{', id",
			"expecting: 'if', 'while', 'System.out.println', '{', '}', id",
			"expecting: '[', '=', id",
			"expecting: 'return'",
			"expecting: 'if', 'while', 'return', 'System.out.println', '{', '}', id",
			"expecting: '[', '='",
			"expecting: 'true', 'false', 'this', 'new', '(', '!', id, number",
			"expecting: 'return', '}'",
			"expecting: '[', ']', ')', '.', ',', ';', '+', '-', '*', '>', '<', '>=', '<=', '&&', '||', '==', '!='",
			"expecting: 'int', id",
			"expecting: ']', ')', '.', ',', ';', '+', '-', '*', '>', '<', '>=', '<=', '&&', '||', '==', '!='",
			"expecting: ']', ')', ',', ';', '+', '-', '*', '>', '<', '>=', '<=', '&&', '||', '==', '!='",
			"expecting: ']', ')', ',', ';', '+', '-', '>', '<', '>=', '<=', '&&', '||', '==', '!='",
			"expecting: ']', ')', ',', ';', '>', '<', '>=', '<=', '&&', '||', '==', '!='",
			"expecting: ')', '&&', '||', '==', '!='",
			"expecting: 'if', 'while', 'else', 'return', 'System.out.println', '{', '}', id",
			"expecting: ']', '&&', '||', '==', '!='",
			"expecting: ';', '&&', '||', '==', '!='",
			"expecting: 'length', id",
			"expecting: '='",
			"expecting: 'public', '}'",
			"expecting: 'true', 'false', 'this', 'new', '(', ')', '!', id, number",
			"expecting: ')', ',', '&&', '||', '==', '!='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 2, 5, 6, 7, 1, 8, 9, 4, 8, 10, 8, 11, 1, 12, 1, 13, 1, 14, 8, 15, 1, 3, 16, 17, 13, 1, 14, 2, 18, 19, 3, 20, 15, 2, 21, 1, 1, 4, 22, 21, 23, 12, 21, 4, 23, 1, 24, 14, 14, 14, 25, 26, 27, 28, 28, 28, 22, 29, 13, 30, 30, 30, 13, 30, 30, 30, 31, 21, 13, 32, 32, 32, 33, 30, 30, 32, 32, 32, 34, 35, 35, 36, 37, 38, 38, 38, 39, 40, 41, 41, 3, 19, 14, 38, 35, 30, 42, 30, 30, 30, 30, 30, 30, 30, 24, 30, 30, 30, 30, 24, 16, 43, 39, 13, 30, 21, 32, 40, 32, 14, 35, 35, 35, 36, 36, 36, 36, 28, 39, 37, 37, 37, 37, 28, 39, 39, 30, 44, 40, 32, 32, 45, 24, 41, 13, 32, 46, 21, 28, 39, 39, 30, 34, 30, 21, 32, 40, 46, 32, 21, 34, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
