/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class TTokNull extends Token
{
    public TTokNull()
    {
        super.setText("null");
    }

    public TTokNull(int line, int pos)
    {
        super.setText("null");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTokNull(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTokNull(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTokNull text.");
    }
}
