/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.parser;

import minijava.lexer.*;
import minijava.node.*;
import minijava.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AProgram */
		    {
			ArrayList list = new0();
			push(goTo(0), list);
		    }
		    break;
                    case 1: /* reduce AMainclass */
		    {
			ArrayList list = new1();
			push(goTo(1), list);
		    }
		    break;
                    case 2: /* reduce AExtClassdecl */
		    {
			ArrayList list = new2();
			push(goTo(2), list);
		    }
		    break;
                    case 3: /* reduce ANonextClassdecl */
		    {
			ArrayList list = new3();
			push(goTo(2), list);
		    }
		    break;
                    case 4: /* reduce AEmptyClassdecl */
		    {
			ArrayList list = new4();
			push(goTo(2), list);
		    }
		    break;
                    case 5: /* reduce ANonemptyVardecl */
		    {
			ArrayList list = new5();
			push(goTo(3), list);
		    }
		    break;
                    case 6: /* reduce AEmptyVardecl */
		    {
			ArrayList list = new6();
			push(goTo(3), list);
		    }
		    break;
                    case 7: /* reduce ANonemptyMethoddecl */
		    {
			ArrayList list = new7();
			push(goTo(4), list);
		    }
		    break;
                    case 8: /* reduce AEmptyMethoddecl */
		    {
			ArrayList list = new8();
			push(goTo(4), list);
		    }
		    break;
                    case 9: /* reduce ANonemptyFormallist */
		    {
			ArrayList list = new9();
			push(goTo(5), list);
		    }
		    break;
                    case 10: /* reduce AEmptyFormallist */
		    {
			ArrayList list = new10();
			push(goTo(5), list);
		    }
		    break;
                    case 11: /* reduce ARemainderFormalrest */
		    {
			ArrayList list = new11();
			push(goTo(6), list);
		    }
		    break;
                    case 12: /* reduce AEmptyFormalrest */
		    {
			ArrayList list = new12();
			push(goTo(6), list);
		    }
		    break;
                    case 13: /* reduce ANonemptyStatementlist */
		    {
			ArrayList list = new13();
			push(goTo(7), list);
		    }
		    break;
                    case 14: /* reduce AEmptyStatementlist */
		    {
			ArrayList list = new14();
			push(goTo(7), list);
		    }
		    break;
                    case 15: /* reduce ANestedStatement */
		    {
			ArrayList list = new15();
			push(goTo(8), list);
		    }
		    break;
                    case 16: /* reduce AIfelseStatement */
		    {
			ArrayList list = new16();
			push(goTo(8), list);
		    }
		    break;
                    case 17: /* reduce AWhileStatement */
		    {
			ArrayList list = new17();
			push(goTo(8), list);
		    }
		    break;
                    case 18: /* reduce APrintStatement */
		    {
			ArrayList list = new18();
			push(goTo(8), list);
		    }
		    break;
                    case 19: /* reduce AAssignStatement */
		    {
			ArrayList list = new19();
			push(goTo(8), list);
		    }
		    break;
                    case 20: /* reduce AVassignStatement */
		    {
			ArrayList list = new20();
			push(goTo(8), list);
		    }
		    break;
                    case 21: /* reduce AInttType */
		    {
			ArrayList list = new21();
			push(goTo(9), list);
		    }
		    break;
                    case 22: /* reduce AIntvType */
		    {
			ArrayList list = new22();
			push(goTo(9), list);
		    }
		    break;
                    case 23: /* reduce AIntmType */
		    {
			ArrayList list = new23();
			push(goTo(9), list);
		    }
		    break;
                    case 24: /* reduce ABoolType */
		    {
			ArrayList list = new24();
			push(goTo(9), list);
		    }
		    break;
                    case 25: /* reduce AClassType */
		    {
			ArrayList list = new25();
			push(goTo(9), list);
		    }
		    break;
                    case 26: /* reduce ANameNoarrayexpr */
		    {
			ArrayList list = new26();
			push(goTo(10), list);
		    }
		    break;
                    case 27: /* reduce ALiteralNoarrayexpr */
		    {
			ArrayList list = new27();
			push(goTo(10), list);
		    }
		    break;
                    case 28: /* reduce ATrueNoarrayexpr */
		    {
			ArrayList list = new28();
			push(goTo(10), list);
		    }
		    break;
                    case 29: /* reduce AFalseNoarrayexpr */
		    {
			ArrayList list = new29();
			push(goTo(10), list);
		    }
		    break;
                    case 30: /* reduce ASelfNoarrayexpr */
		    {
			ArrayList list = new30();
			push(goTo(10), list);
		    }
		    break;
                    case 31: /* reduce AParexpNoarrayexpr */
		    {
			ArrayList list = new31();
			push(goTo(10), list);
		    }
		    break;
                    case 32: /* reduce AVaccessNoarrayexpr */
		    {
			ArrayList list = new32();
			push(goTo(10), list);
		    }
		    break;
                    case 33: /* reduce ALengthNoarrayexpr */
		    {
			ArrayList list = new33();
			push(goTo(10), list);
		    }
		    break;
                    case 34: /* reduce AMaccessNoarrayexpr */
		    {
			ArrayList list = new34();
			push(goTo(10), list);
		    }
		    break;
                    case 35: /* reduce ANewcNoarrayexpr */
		    {
			ArrayList list = new35();
			push(goTo(10), list);
		    }
		    break;
                    case 36: /* reduce ANewarrPrimaryexpr */
		    {
			ArrayList list = new36();
			push(goTo(11), list);
		    }
		    break;
                    case 37: /* reduce ANextPrimaryexpr */
		    {
			ArrayList list = new37();
			push(goTo(11), list);
		    }
		    break;
                    case 38: /* reduce ANonemptyMatrixaccess */
		    {
			ArrayList list = new38();
			push(goTo(12), list);
		    }
		    break;
                    case 39: /* reduce AEmptyMatrixaccess */
		    {
			ArrayList list = new39();
			push(goTo(12), list);
		    }
		    break;
                    case 40: /* reduce ANotUnaryexpr */
		    {
			ArrayList list = new40();
			push(goTo(13), list);
		    }
		    break;
                    case 41: /* reduce ANextUnaryexpr */
		    {
			ArrayList list = new41();
			push(goTo(13), list);
		    }
		    break;
                    case 42: /* reduce AMultIpexpr */
		    {
			ArrayList list = new42();
			push(goTo(14), list);
		    }
		    break;
                    case 43: /* reduce ANextIpexpr */
		    {
			ArrayList list = new43();
			push(goTo(14), list);
		    }
		    break;
                    case 44: /* reduce APlusIaexpr */
		    {
			ArrayList list = new44();
			push(goTo(15), list);
		    }
		    break;
                    case 45: /* reduce AMinusIaexpr */
		    {
			ArrayList list = new45();
			push(goTo(15), list);
		    }
		    break;
                    case 46: /* reduce ANextIaexpr */
		    {
			ArrayList list = new46();
			push(goTo(15), list);
		    }
		    break;
                    case 47: /* reduce AGreaterBexpr */
		    {
			ArrayList list = new47();
			push(goTo(16), list);
		    }
		    break;
                    case 48: /* reduce ALessBexpr */
		    {
			ArrayList list = new48();
			push(goTo(16), list);
		    }
		    break;
                    case 49: /* reduce ANextBexpr */
		    {
			ArrayList list = new49();
			push(goTo(16), list);
		    }
		    break;
                    case 50: /* reduce AAndExpr */
		    {
			ArrayList list = new50();
			push(goTo(17), list);
		    }
		    break;
                    case 51: /* reduce ANextExpr */
		    {
			ArrayList list = new51();
			push(goTo(17), list);
		    }
		    break;
                    case 52: /* reduce ANonemptyExprlist */
		    {
			ArrayList list = new52();
			push(goTo(18), list);
		    }
		    break;
                    case 53: /* reduce AEmptyExprlist */
		    {
			ArrayList list = new53();
			push(goTo(18), list);
		    }
		    break;
                    case 54: /* reduce ARemainderExprrest */
		    {
			ArrayList list = new54();
			push(goTo(19), list);
		    }
		    break;
                    case 55: /* reduce AEmptyExprrest */
		    {
			ArrayList list = new55();
			push(goTo(19), list);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AProgram */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        PMainclass pmainclassNode2;
        LinkedList listNode4 = new LinkedList();
        pmainclassNode2 = (PMainclass)nodeArrayList1.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AProgram(pmainclassNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AMainclass */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList17 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList16 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList15 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMainclass pmainclassNode1;
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList12.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList15.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pmainclassNode1 = new AMainclass(tidNode2, tidNode3, listNode5);
        }
	nodeList.add(pmainclassNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AExtClassdecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode9 = new LinkedList();
        {
            // Block
        PNextclass pnextclassNode1;
        LinkedList listNode8 = new LinkedList();
        {
            // Block
        TId tidNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList6.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList7.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }

        pnextclassNode1 = new AExtNextclass(tidNode2, tidNode3, listNode5, listNode7);
        }
        listNode8 = (LinkedList)nodeArrayList9.get(0);
	if(pnextclassNode1 != null)
	{
	  listNode9.add(pnextclassNode1);
	}
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
	nodeList.add(listNode9);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce ANonextClassdecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode8 = new LinkedList();
        {
            // Block
        PNextclass pnextclassNode1;
        LinkedList listNode7 = new LinkedList();
        {
            // Block
        TId tidNode2;
        LinkedList listNode4 = new LinkedList();
        LinkedList listNode6 = new LinkedList();
        tidNode2 = (TId)nodeArrayList2.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList4.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        {
            // Block
        LinkedList listNode5 = new LinkedList();
        listNode5 = (LinkedList)nodeArrayList5.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }

        pnextclassNode1 = new ANonextNextclass(tidNode2, listNode4, listNode6);
        }
        listNode7 = (LinkedList)nodeArrayList7.get(0);
	if(pnextclassNode1 != null)
	{
	  listNode8.add(pnextclassNode1);
	}
	if(listNode7 != null)
	{
	  listNode8.addAll(listNode7);
	}
        }
	nodeList.add(listNode8);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AEmptyClassdecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce ANonemptyVardecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        LinkedList listNode1 = new LinkedList();
        PVar pvarNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        {
            // Block
        PType ptypeNode3;
        TId tidNode4;
        ptypeNode3 = (PType)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);

        pvarNode2 = new AVar(ptypeNode3, tidNode4);
        }
	if(listNode1 != null)
	{
	  listNode5.addAll(listNode1);
	}
	if(pvarNode2 != null)
	{
	  listNode5.add(pvarNode2);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AEmptyVardecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce ANonemptyMethoddecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList14 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList13 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList12 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList11 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList10 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode12 = new LinkedList();
        {
            // Block
        PMethod pmethodNode1;
        LinkedList listNode11 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        LinkedList listNode7 = new LinkedList();
        LinkedList listNode9 = new LinkedList();
        PExpression pexpressionNode10;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        {
            // Block
        LinkedList listNode6 = new LinkedList();
        listNode6 = (LinkedList)nodeArrayList8.get(0);
	if(listNode6 != null)
	{
	  listNode7.addAll(listNode6);
	}
        }
        {
            // Block
        LinkedList listNode8 = new LinkedList();
        listNode8 = (LinkedList)nodeArrayList9.get(0);
	if(listNode8 != null)
	{
	  listNode9.addAll(listNode8);
	}
        }
        pexpressionNode10 = (PExpression)nodeArrayList11.get(0);

        pmethodNode1 = new AMethod(ptypeNode2, tidNode3, listNode5, listNode7, listNode9, pexpressionNode10);
        }
        listNode11 = (LinkedList)nodeArrayList14.get(0);
	if(pmethodNode1 != null)
	{
	  listNode12.add(pmethodNode1);
	}
	if(listNode11 != null)
	{
	  listNode12.addAll(listNode11);
	}
        }
	nodeList.add(listNode12);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AEmptyMethoddecl */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce ANonemptyFormallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        PVar pvarNode1;
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);

        pvarNode1 = new AVar(ptypeNode2, tidNode3);
        }
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(pvarNode1 != null)
	{
	  listNode5.add(pvarNode1);
	}
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AEmptyFormallist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce ARemainderFormalrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode5 = new LinkedList();
        {
            // Block
        PVar pvarNode1;
        LinkedList listNode4 = new LinkedList();
        {
            // Block
        PType ptypeNode2;
        TId tidNode3;
        ptypeNode2 = (PType)nodeArrayList2.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);

        pvarNode1 = new AVar(ptypeNode2, tidNode3);
        }
        listNode4 = (LinkedList)nodeArrayList4.get(0);
	if(pvarNode1 != null)
	{
	  listNode5.add(pvarNode1);
	}
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
	nodeList.add(listNode5);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AEmptyFormalrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce ANonemptyStatementlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PStatement pstatementNode1;
        LinkedList listNode2 = new LinkedList();
        pstatementNode1 = (PStatement)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pstatementNode1 != null)
	{
	  listNode3.add(pstatementNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce AEmptyStatementlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce ANestedStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        LinkedList listNode2 = new LinkedList();
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstatementNode1 = new AManyStatement(listNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AIfelseStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PStatement pstatementNode3;
        PStatement pstatementNode4;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);
        pstatementNode4 = (PStatement)nodeArrayList7.get(0);

        pstatementNode1 = new AIfStatement(pexpressionNode2, pstatementNode3, pstatementNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AWhileStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PStatement pstatementNode3;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);
        pstatementNode3 = (PStatement)nodeArrayList5.get(0);

        pstatementNode1 = new AWhileStatement(pexpressionNode2, pstatementNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce APrintStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new APrintStatement(pexpressionNode2);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AAssignStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExpression pexpressionNode3;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pstatementNode1 = new AAtbStatement(tidNode2, pexpressionNode3);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce AVassignStatement */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PStatement pstatementNode1;
        {
            // Block
        TId tidNode2;
        PExpression pexpressionNode3;
        PExpression pexpressionNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);
        pexpressionNode4 = (PExpression)nodeArrayList6.get(0);

        pstatementNode1 = new AVatbStatement(tidNode2, pexpressionNode3, pexpressionNode4);
        }
	nodeList.add(pstatementNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AInttType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TIntt tinttNode2;
        tinttNode2 = (TIntt)nodeArrayList1.get(0);

        ptypeNode1 = new AInttType(tinttNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AIntvType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TIntv tintvNode2;
        tintvNode2 = (TIntv)nodeArrayList1.get(0);

        ptypeNode1 = new AIntvType(tintvNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AIntmType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TIntm tintmNode2;
        tintmNode2 = (TIntm)nodeArrayList1.get(0);

        ptypeNode1 = new AIntmType(tintmNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce ABoolType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBool tboolNode2;
        tboolNode2 = (TBool)nodeArrayList1.get(0);

        ptypeNode1 = new ABoolType(tboolNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AClassType */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        ptypeNode1 = new AClassType(tidNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce ANameNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        pexpressionNode1 = new AVarExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce ALiteralNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexpressionNode1 = new ANumberExpression(tnumberNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce ATrueNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TTrue ttrueNode2;
        ttrueNode2 = (TTrue)nodeArrayList1.get(0);

        pexpressionNode1 = new ABtrueExpression(ttrueNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce AFalseNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TFalse tfalseNode2;
        tfalseNode2 = (TFalse)nodeArrayList1.get(0);

        pexpressionNode1 = new ABfalseExpression(tfalseNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce ASelfNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TThis tthisNode2;
        tthisNode2 = (TThis)nodeArrayList1.get(0);

        pexpressionNode1 = new ASelfExpression(tthisNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce AParexpNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AVaccessNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AVectorExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce ALengthNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);

        pexpressionNode1 = new ALengthExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new34() /* reduce AMaccessNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        TId tidNode3;
        LinkedList listNode5 = new LinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList3.get(0);
        {
            // Block
        LinkedList listNode4 = new LinkedList();
        listNode4 = (LinkedList)nodeArrayList5.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pexpressionNode1 = new AMcallExpression(pexpressionNode2, tidNode3, listNode5);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new35() /* reduce ANewcNoarrayexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList2.get(0);

        pexpressionNode1 = new ANewobjExpression(tidNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new36() /* reduce ANewarrPrimaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        LinkedList listNode4 = new LinkedList();
        pexpressionNode2 = (PExpression)nodeArrayList4.get(0);
        {
            // Block
        LinkedList listNode3 = new LinkedList();
        listNode3 = (LinkedList)nodeArrayList6.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pexpressionNode1 = new ANewvecExpression(pexpressionNode2, listNode4);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new37() /* reduce ANextPrimaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new38() /* reduce ANonemptyMatrixaccess */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode2 = new LinkedList();
        {
            // Block
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode2.add(pexpressionNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new39() /* reduce AEmptyMatrixaccess */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new40() /* reduce ANotUnaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        pexpressionNode2 = (PExpression)nodeArrayList2.get(0);

        pexpressionNode1 = new ANotExpression(pexpressionNode2);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new41() /* reduce ANextUnaryexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new42() /* reduce AMultIpexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMultExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new43() /* reduce ANextIpexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new44() /* reduce APlusIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new APlusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new45() /* reduce AMinusIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AMinusExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new46() /* reduce ANextIaexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new47() /* reduce AGreaterBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AGthanExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new48() /* reduce ALessBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new ALthanExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new49() /* reduce ANextBexpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new50() /* reduce AAndExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        {
            // Block
        PExpression pexpressionNode2;
        PExpression pexpressionNode3;
        pexpressionNode2 = (PExpression)nodeArrayList1.get(0);
        pexpressionNode3 = (PExpression)nodeArrayList3.get(0);

        pexpressionNode1 = new AAndExpression(pexpressionNode2, pexpressionNode3);
        }
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new51() /* reduce ANextExpr */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExpression pexpressionNode1;
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
	nodeList.add(pexpressionNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new52() /* reduce ANonemptyExprlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExpression pexpressionNode1;
        LinkedList listNode2 = new LinkedList();
        pexpressionNode1 = (PExpression)nodeArrayList1.get(0);
        listNode2 = (LinkedList)nodeArrayList2.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode3.add(pexpressionNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new53() /* reduce AEmptyExprlist */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new54() /* reduce ARemainderExprrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        LinkedList listNode3 = new LinkedList();
        {
            // Block
        PExpression pexpressionNode1;
        LinkedList listNode2 = new LinkedList();
        pexpressionNode1 = (PExpression)nodeArrayList2.get(0);
        listNode2 = (LinkedList)nodeArrayList3.get(0);
	if(pexpressionNode1 != null)
	{
	  listNode3.add(pexpressionNode1);
	}
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new55() /* reduce AEmptyExprrest */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        LinkedList listNode1 = new LinkedList();
        {
            // Block
        }
	nodeList.add(listNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {4, SHIFT, 1}, },
			{{-1, ERROR, 1}, {38, SHIFT, 4}, },
			{{-1, ERROR, 2}, {40, ACCEPT, -1}, },
			{{-1, REDUCE, 4}, {4, SHIFT, 5}, },
			{{-1, ERROR, 4}, {25, SHIFT, 7}, },
			{{-1, ERROR, 5}, {38, SHIFT, 8}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 7}, {5, SHIFT, 9}, },
			{{-1, ERROR, 8}, {6, SHIFT, 10}, {25, SHIFT, 11}, },
			{{-1, ERROR, 9}, {18, SHIFT, 12}, },
			{{-1, ERROR, 10}, {38, SHIFT, 13}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 12}, {19, SHIFT, 15}, },
			{{-1, ERROR, 13}, {25, SHIFT, 16}, },
			{{-1, REDUCE, 8}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {5, SHIFT, 21}, {38, SHIFT, 22}, },
			{{-1, ERROR, 15}, {20, SHIFT, 25}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 21}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {38, SHIFT, 22}, },
			{{-1, REDUCE, 25}, },
			{{-1, ERROR, 23}, {26, SHIFT, 28}, },
			{{-1, ERROR, 24}, {38, SHIFT, 29}, },
			{{-1, ERROR, 25}, {23, SHIFT, 30}, },
			{{-1, REDUCE, 8}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {5, SHIFT, 21}, {38, SHIFT, 22}, },
			{{-1, ERROR, 27}, {38, SHIFT, 32}, },
			{{-1, REDUCE, 4}, {4, SHIFT, 5}, },
			{{-1, ERROR, 29}, {29, SHIFT, 34}, },
			{{-1, ERROR, 30}, {16, SHIFT, 35}, },
			{{-1, ERROR, 31}, {26, SHIFT, 36}, },
			{{-1, ERROR, 32}, {23, SHIFT, 37}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 35}, {21, SHIFT, 38}, },
			{{-1, REDUCE, 4}, {4, SHIFT, 5}, },
			{{-1, REDUCE, 10}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {38, SHIFT, 22}, },
			{{-1, ERROR, 38}, {22, SHIFT, 42}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 40}, {24, SHIFT, 43}, },
			{{-1, ERROR, 41}, {38, SHIFT, 44}, },
			{{-1, ERROR, 42}, {38, SHIFT, 45}, },
			{{-1, ERROR, 43}, {25, SHIFT, 46}, },
			{{-1, REDUCE, 12}, {28, SHIFT, 47}, },
			{{-1, ERROR, 45}, {24, SHIFT, 49}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 47}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {38, SHIFT, 22}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 49}, {25, SHIFT, 52}, },
			{{-1, REDUCE, 14}, {0, SHIFT, 17}, {1, SHIFT, 18}, {2, SHIFT, 19}, {3, SHIFT, 20}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 57}, },
			{{-1, ERROR, 51}, {38, SHIFT, 60}, },
			{{-1, REDUCE, 14}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, ERROR, 53}, {23, SHIFT, 63}, },
			{{-1, ERROR, 54}, {23, SHIFT, 64}, },
			{{-1, ERROR, 55}, {23, SHIFT, 65}, },
			{{-1, REDUCE, 14}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, REDUCE, 25}, {21, SHIFT, 67}, {37, SHIFT, 68}, },
			{{-1, ERROR, 58}, {10, SHIFT, 69}, },
			{{-1, REDUCE, 14}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, REDUCE, 12}, {28, SHIFT, 47}, },
			{{-1, ERROR, 61}, {21, SHIFT, 67}, {37, SHIFT, 68}, },
			{{-1, ERROR, 62}, {26, SHIFT, 72}, },
			{{-1, ERROR, 63}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 64}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 65}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 66}, {26, SHIFT, 90}, },
			{{-1, ERROR, 67}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 68}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 69}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 72}, {26, SHIFT, 94}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 76}, {0, SHIFT, 95}, {38, SHIFT, 96}, },
			{{-1, ERROR, 77}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 78}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, REDUCE, 26}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 37}, {21, SHIFT, 99}, },
			{{-1, REDUCE, 41}, {27, SHIFT, 100}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 46}, {32, SHIFT, 101}, },
			{{-1, REDUCE, 49}, {30, SHIFT, 102}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 51}, {33, SHIFT, 104}, {34, SHIFT, 105}, },
			{{-1, ERROR, 87}, {24, SHIFT, 106}, {35, SHIFT, 107}, },
			{{-1, ERROR, 88}, {24, SHIFT, 108}, {35, SHIFT, 107}, },
			{{-1, ERROR, 89}, {24, SHIFT, 109}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 91}, {22, SHIFT, 110}, {35, SHIFT, 107}, },
			{{-1, ERROR, 92}, {29, SHIFT, 111}, {35, SHIFT, 107}, },
			{{-1, ERROR, 93}, {29, SHIFT, 112}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 95}, {21, SHIFT, 113}, },
			{{-1, ERROR, 96}, {23, SHIFT, 114}, },
			{{-1, ERROR, 97}, {24, SHIFT, 115}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 40}, },
			{{-1, ERROR, 99}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 100}, {15, SHIFT, 117}, {38, SHIFT, 118}, },
			{{-1, ERROR, 101}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 102}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 103}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 104}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 105}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 106}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, ERROR, 107}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 108}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, ERROR, 109}, {29, SHIFT, 127}, },
			{{-1, ERROR, 110}, {37, SHIFT, 128}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 112}, {26, SHIFT, 129}, },
			{{-1, ERROR, 113}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 114}, {24, SHIFT, 131}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 116}, {22, SHIFT, 132}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 33}, },
			{{-1, ERROR, 118}, {23, SHIFT, 133}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 44}, {32, SHIFT, 101}, },
			{{-1, REDUCE, 45}, {32, SHIFT, 101}, },
			{{-1, REDUCE, 47}, {30, SHIFT, 102}, {31, SHIFT, 103}, },
			{{-1, REDUCE, 48}, {30, SHIFT, 102}, {31, SHIFT, 103}, },
			{{-1, ERROR, 124}, {9, SHIFT, 134}, },
			{{-1, REDUCE, 50}, {33, SHIFT, 104}, {34, SHIFT, 105}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 128}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, REDUCE, 8}, {5, SHIFT, 21}, },
			{{-1, ERROR, 130}, {22, SHIFT, 137}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 35}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 53}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, ERROR, 134}, {7, SHIFT, 53}, {8, SHIFT, 54}, {17, SHIFT, 55}, {25, SHIFT, 56}, {38, SHIFT, 61}, },
			{{-1, ERROR, 135}, {29, SHIFT, 141}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 39}, {21, SHIFT, 142}, },
			{{-1, REDUCE, 55}, {28, SHIFT, 144}, {35, SHIFT, 107}, },
			{{-1, ERROR, 139}, {24, SHIFT, 146}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 142}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, REDUCE, 36}, },
			{{-1, ERROR, 144}, {11, SHIFT, 73}, {12, SHIFT, 74}, {13, SHIFT, 75}, {14, SHIFT, 76}, {23, SHIFT, 77}, {36, SHIFT, 78}, {38, SHIFT, 79}, {39, SHIFT, 80}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 34}, },
			{{-1, ERROR, 147}, {22, SHIFT, 149}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 55}, {28, SHIFT, 144}, {35, SHIFT, 107}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 54}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 2}, },
			{{-1, 3}, },
			{{-1, 6}, {28, 33}, {36, 39}, },
			{{-1, 14}, {16, 26}, {46, 50}, },
			{{-1, 23}, {26, 31}, {129, 136}, },
			{{-1, 40}, },
			{{-1, 48}, {60, 71}, },
			{{-1, 58}, {52, 62}, {56, 66}, {59, 70}, },
			{{-1, 59}, {106, 124}, {108, 126}, {134, 140}, },
			{{-1, 24}, {21, 27}, {37, 41}, {47, 51}, },
			{{-1, 81}, },
			{{-1, 82}, },
			{{-1, 143}, },
			{{-1, 83}, {78, 98}, {101, 119}, },
			{{-1, 84}, {102, 120}, {103, 121}, },
			{{-1, 85}, {104, 122}, {105, 123}, },
			{{-1, 86}, {107, 125}, },
			{{-1, 87}, {64, 88}, {65, 89}, {67, 91}, {68, 92}, {69, 93}, {77, 97}, {99, 116}, {113, 130}, {128, 135}, {133, 138}, {142, 147}, {144, 148}, },
			{{-1, 139}, },
			{{-1, 145}, {148, 150}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'class'",
			"expecting: id",
			"expecting: EOF",
			"expecting: 'class', EOF",
			"expecting: '{'",
			"expecting: 'public'",
			"expecting: 'extends', '{'",
			"expecting: 'static'",
			"expecting: 'int', intv, intm, 'boolean', 'public', '}', id",
			"expecting: 'void'",
			"expecting: 'main'",
			"expecting: 'int', intv, intm, 'boolean', id",
			"expecting: '}'",
			"expecting: '('",
			"expecting: ';'",
			"expecting: 'String'",
			"expecting: 'int', intv, intm, 'boolean', 'public', 'if', 'while', 'return', 'System.out.println', '{', '}', id",
			"expecting: '['",
			"expecting: 'int', intv, intm, 'boolean', ')', id",
			"expecting: ']'",
			"expecting: ')'",
			"expecting: ')', ','",
			"expecting: 'int', intv, intm, 'boolean', 'if', 'while', 'return', 'System.out.println', '{', id",
			"expecting: 'if', 'while', 'System.out.println', '{', '}', id",
			"expecting: '[', '=', id",
			"expecting: 'return'",
			"expecting: 'if', 'while', 'return', 'System.out.println', '{', '}', id",
			"expecting: '[', '='",
			"expecting: 'true', 'false', 'this', 'new', '(', '!', id, number",
			"expecting: 'return', '}'",
			"expecting: '[', ']', ')', '.', ',', ';', '+', '-', '*', '>', '<', '&&'",
			"expecting: 'int', id",
			"expecting: ']', ')', '.', ',', ';', '+', '-', '*', '>', '<', '&&'",
			"expecting: ']', ')', ',', ';', '+', '-', '*', '>', '<', '&&'",
			"expecting: ']', ')', ',', ';', '+', '-', '>', '<', '&&'",
			"expecting: ']', ')', ',', ';', '>', '<', '&&'",
			"expecting: ')', '&&'",
			"expecting: 'if', 'while', 'else', 'return', 'System.out.println', '{', '}', id",
			"expecting: ']', '&&'",
			"expecting: ';', '&&'",
			"expecting: 'length', id",
			"expecting: 'if', 'while', 'System.out.println', '{', id",
			"expecting: '='",
			"expecting: 'else'",
			"expecting: 'public', '}'",
			"expecting: 'true', 'false', 'this', 'new', '(', ')', '!', id, number",
			"expecting: ')', ',', '&&'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 1, 2, 5, 6, 7, 1, 8, 9, 4, 8, 10, 8, 1, 1, 1, 1, 11, 1, 12, 1, 13, 8, 1, 3, 14, 15, 12, 13, 2, 16, 17, 3, 18, 19, 2, 20, 1, 1, 4, 21, 20, 22, 11, 20, 4, 22, 1, 23, 13, 13, 13, 23, 24, 25, 26, 21, 27, 12, 28, 28, 28, 12, 28, 28, 28, 29, 20, 12, 30, 30, 30, 31, 28, 28, 30, 30, 30, 32, 33, 33, 34, 35, 36, 36, 36, 37, 38, 39, 39, 3, 17, 13, 36, 33, 28, 40, 28, 28, 28, 28, 28, 41, 28, 41, 14, 42, 37, 12, 28, 20, 30, 38, 30, 13, 33, 33, 33, 34, 34, 43, 35, 37, 37, 28, 44, 38, 30, 30, 45, 41, 39, 12, 30, 46, 20, 37, 37, 28, 32, 28, 20, 30, 38, 46, 32, 20, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
