/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AArrayType extends PType
{
    private TInt _vetor_;
    private TLcol _lcol_;
    private TRcol _rcol_;

    public AArrayType()
    {
        // Constructor
    }

    public AArrayType(
        @SuppressWarnings("hiding") TInt _vetor_,
        @SuppressWarnings("hiding") TLcol _lcol_,
        @SuppressWarnings("hiding") TRcol _rcol_)
    {
        // Constructor
        setVetor(_vetor_);

        setLcol(_lcol_);

        setRcol(_rcol_);

    }

    @Override
    public Object clone()
    {
        return new AArrayType(
            cloneNode(this._vetor_),
            cloneNode(this._lcol_),
            cloneNode(this._rcol_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayType(this);
    }

    public TInt getVetor()
    {
        return this._vetor_;
    }

    public void setVetor(TInt node)
    {
        if(this._vetor_ != null)
        {
            this._vetor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vetor_ = node;
    }

    public TLcol getLcol()
    {
        return this._lcol_;
    }

    public void setLcol(TLcol node)
    {
        if(this._lcol_ != null)
        {
            this._lcol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lcol_ = node;
    }

    public TRcol getRcol()
    {
        return this._rcol_;
    }

    public void setRcol(TRcol node)
    {
        if(this._rcol_ != null)
        {
            this._rcol_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rcol_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vetor_)
            + toString(this._lcol_)
            + toString(this._rcol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vetor_ == child)
        {
            this._vetor_ = null;
            return;
        }

        if(this._lcol_ == child)
        {
            this._lcol_ = null;
            return;
        }

        if(this._rcol_ == child)
        {
            this._rcol_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vetor_ == oldChild)
        {
            setVetor((TInt) newChild);
            return;
        }

        if(this._lcol_ == oldChild)
        {
            setLcol((TLcol) newChild);
            return;
        }

        if(this._rcol_ == oldChild)
        {
            setRcol((TRcol) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
