/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AInttType extends PType
{
    private TIntt _intt_;

    public AInttType()
    {
        // Constructor
    }

    public AInttType(
        @SuppressWarnings("hiding") TIntt _intt_)
    {
        // Constructor
        setIntt(_intt_);

    }

    @Override
    public Object clone()
    {
        return new AInttType(
            cloneNode(this._intt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInttType(this);
    }

    public TIntt getIntt()
    {
        return this._intt_;
    }

    public void setIntt(TIntt node)
    {
        if(this._intt_ != null)
        {
            this._intt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intt_ == child)
        {
            this._intt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intt_ == oldChild)
        {
            setIntt((TIntt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
