/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class AMatrixExpression extends PExpression
{
    private PExpression _l_;
    private PExpression _i_;
    private PExpression _e_;

    public AMatrixExpression()
    {
        // Constructor
    }

    public AMatrixExpression(
        @SuppressWarnings("hiding") PExpression _l_,
        @SuppressWarnings("hiding") PExpression _i_,
        @SuppressWarnings("hiding") PExpression _e_)
    {
        // Constructor
        setL(_l_);

        setI(_i_);

        setE(_e_);

    }

    @Override
    public Object clone()
    {
        return new AMatrixExpression(
            cloneNode(this._l_),
            cloneNode(this._i_),
            cloneNode(this._e_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatrixExpression(this);
    }

    public PExpression getL()
    {
        return this._l_;
    }

    public void setL(PExpression node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public PExpression getI()
    {
        return this._i_;
    }

    public void setI(PExpression node)
    {
        if(this._i_ != null)
        {
            this._i_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._i_ = node;
    }

    public PExpression getE()
    {
        return this._e_;
    }

    public void setE(PExpression node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._i_)
            + toString(this._e_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._i_ == child)
        {
            this._i_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PExpression) newChild);
            return;
        }

        if(this._i_ == oldChild)
        {
            setI((PExpression) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
