/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.node;

import minijava.analysis.*;

@SuppressWarnings("nls")
public final class ANotexpExp2 extends PExp2
{
    private TNot _not_;
    private PExp _notExp_;

    public ANotexpExp2()
    {
        // Constructor
    }

    public ANotexpExp2(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PExp _notExp_)
    {
        // Constructor
        setNot(_not_);

        setNotExp(_notExp_);

    }

    @Override
    public Object clone()
    {
        return new ANotexpExp2(
            cloneNode(this._not_),
            cloneNode(this._notExp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotexpExp2(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PExp getNotExp()
    {
        return this._notExp_;
    }

    public void setNotExp(PExp node)
    {
        if(this._notExp_ != null)
        {
            this._notExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._notExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._notExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._notExp_ == child)
        {
            this._notExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._notExp_ == oldChild)
        {
            setNotExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
