/* This file was generated by SableCC (http://www.sablecc.org/). */

package minijava.analysis;

import minijava.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);

    void caseTIntt(TIntt node);
    void caseTBool(TBool node);
    void caseTClasstk(TClasstk node);
    void caseTPublic(TPublic node);
    void caseTExtends(TExtends node);
    void caseTIf(TIf node);
    void caseTWhile(TWhile node);
    void caseTElse(TElse node);
    void caseTReturn(TReturn node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTThis(TThis node);
    void caseTNew(TNew node);
    void caseTLength(TLength node);
    void caseTString(TString node);
    void caseTPrint(TPrint node);
    void caseTLbrace(TLbrace node);
    void caseTRbrace(TRbrace node);
    void caseTLparen(TLparen node);
    void caseTRparen(TRparen node);
    void caseTLcurbr(TLcurbr node);
    void caseTRcurbr(TRcurbr node);
    void caseTDot(TDot node);
    void caseTComma(TComma node);
    void caseTSemi(TSemi node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTTimes(TTimes node);
    void caseTGt(TGt node);
    void caseTLt(TLt node);
    void caseTAnd(TAnd node);
    void caseTNeg(TNeg node);
    void caseTEq(TEq node);
    void caseTId(TId node);
    void caseTNumber(TNumber node);
    void caseTBlank(TBlank node);
    void caseTComment(TComment node);
    void caseEOF(EOF node);
}
